-- ============================================================
-- 三益穿线管理系统 V1.1 数据库迁移脚本
-- 执行前必须：pg_dump 全量备份！
-- 数据库：PostgreSQL
-- 预计耗时：< 5 分钟（数据量 < 10万条）
-- ============================================================

BEGIN;

-- ============================================================
-- 模块一：数据模型重构（羽网合并）
-- ============================================================

-- ----------------------------------------
-- 1.1 统一 player 表（原 player + tennis_player 合并）
-- ----------------------------------------
CREATE TABLE player_new (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(50)  NOT NULL,
    phone           VARCHAR(20)  NOT NULL DEFAULT '',
    gender          SMALLINT     DEFAULT 0 COMMENT '0-未知 1-男 2-女',
    sport_type      VARCHAR(10)  NOT NULL DEFAULT 'BADMINTON' COMMENT '运动类型: BADMINTON-羽毛球 TENNIS-网球 DUAL-双修',
    ranking         VARCHAR(50)  DEFAULT '' COMMENT '网球排名（仅网球有效）',
    photo_url       VARCHAR(500) DEFAULT '',
    skill_level     VARCHAR(20)  DEFAULT '' COMMENT '水平等级',
    progress_notes  TEXT         DEFAULT '' COMMENT '近期进步/备注',
    remark          VARCHAR(500) DEFAULT '',
    country         VARCHAR(50)  DEFAULT '' COMMENT '国家/地区',
    tenant_id       BIGINT       DEFAULT NULL COMMENT '所属租户',
    deleted         SMALLINT     NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE player_new IS '统一球员表（羽毛球+网球）';
CREATE INDEX idx_player_phone ON player_new(phone);
CREATE INDEX idx_player_tenant ON player_new(tenant_id);
CREATE INDEX idx_player_sport ON player_new(sport_type);

-- 迁移羽毛球 player 数据
INSERT INTO player_new (id, name, phone, gender, sport_type, ranking, photo_url,
                         skill_level, progress_notes, remark, country, tenant_id, deleted, created_at, updated_at)
SELECT id, name, phone, gender, 'BADMINTON', '', photo_url, skill_level, progress_notes,
       remark, '', NULL, deleted, created_at, updated_at
FROM player;

-- 迁移网球 tennis_player 数据（不指定id，使用新序列）
INSERT INTO player_new (name, phone, gender, sport_type, ranking, photo_url,
                         skill_level, progress_notes, remark, country, tenant_id, deleted, created_at, updated_at)
SELECT name, phone, gender, 'TENNIS', ranking, photo_url, skill_level, progress_notes,
       remark, '', NULL, deleted, created_at, updated_at
FROM tennis_player;

-- 更新序列值
SELECT setval('player_new_id_seq', (SELECT MAX(id) FROM player_new));

-- ----------------------------------------
-- 1.2 统一 racket 表（原 racket + tennis_racket 合并）
-- ----------------------------------------
CREATE TABLE racket_new (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_type      VARCHAR(10)  NOT NULL DEFAULT 'BADMINTON' COMMENT '运动类型',
    brand           VARCHAR(100) NOT NULL,
    model           VARCHAR(100) NOT NULL DEFAULT '',
    spec            VARCHAR(50)  DEFAULT '' COMMENT '羽毛球规格(如 4U/3U/G5)',
    head_size       VARCHAR(20)  DEFAULT '' COMMENT '拍面大小(平方英寸)',
    string_pattern  VARCHAR(20)  DEFAULT '' COMMENT '线床规格(如 16x19)',
    weight          VARCHAR(20)  DEFAULT '' COMMENT '空拍重量(克)',
    balance         VARCHAR(20)  DEFAULT '' COMMENT '平衡点(mm)',
    remark          VARCHAR(500) DEFAULT '',
    tenant_id       BIGINT       DEFAULT NULL,
    deleted         SMALLINT     NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE racket_new IS '统一球拍表（羽毛球+网球）';
CREATE INDEX idx_racket_brand ON racket_new(brand);
CREATE INDEX idx_racket_sport ON racket_new(sport_type);

-- 迁移羽毛球 racket 数据
INSERT INTO racket_new (id, sport_type, brand, model, spec, head_size, string_pattern, weight, balance, remark, tenant_id, deleted, created_at, updated_at)
SELECT id, 'BADMINTON', brand, model, spec, '', '', '', '', remark, NULL, deleted, created_at, updated_at
FROM racket;

-- 迁移网球 tennis_racket 数据
INSERT INTO racket_new (sport_type, brand, model, spec, head_size, string_pattern, weight, balance, remark, tenant_id, deleted, created_at, updated_at)
SELECT 'TENNIS', brand, model, '', head_size, string_pattern, weight, balance, remark, NULL, deleted, created_at, updated_at
FROM tennis_racket;

-- 更新序列值
SELECT setval('racket_new_id_seq', (SELECT MAX(id) FROM racket_new));

-- ----------------------------------------
-- 1.3 string_info 表增加字段（原地修改）
-- ----------------------------------------
ALTER TABLE string_info ADD COLUMN IF NOT EXISTS sport_type VARCHAR(10) NOT NULL DEFAULT 'BADMINTON' COMMENT '运动类型: BADMINTON-羽毛球 TENNIS-网球';
ALTER TABLE string_info ADD COLUMN IF NOT EXISTS tenant_id  BIGINT DEFAULT NULL COMMENT '所属租户';
COMMENT ON COLUMN string_info.sport_type IS '运动类型: BADMINTON-羽毛球 TENNIS-网球';
CREATE INDEX IF NOT EXISTS idx_string_sport ON string_info(sport_type);
CREATE INDEX IF NOT EXISTS idx_string_tenant ON string_info(tenant_id);

-- 迁移网球 tennis_string_info 数据
INSERT INTO string_info (brand, model, color, diameter, sport_type, remark, deleted, created_at, updated_at)
SELECT brand, model, color, NULL, 'TENNIS', remark, deleted, created_at, updated_at
FROM tennis_string_info;

-- ----------------------------------------
-- 1.4 stringing_order 表改造（新增字段 + sport_type）
-- ----------------------------------------
-- 运动类型字段（通过 player_new 关联更新）
ALTER TABLE stringing_order ADD COLUMN IF NOT EXISTS sport_type VARCHAR(10) NOT NULL DEFAULT 'BADMINTON' COMMENT '运动类型';
CREATE INDEX IF NOT EXISTS idx_order_sport ON stringing_order(sport_type);

-- 支付相关字段
ALTER TABLE stringing_order ADD COLUMN IF NOT EXISTS pay_status      VARCHAR(20) NOT NULL DEFAULT 'UNPAID' COMMENT '支付状态: UNPAID-未付 PARTIAL-部分支付 PAID-已结清 CREDIT-挂账';
ALTER TABLE stringing_order ADD COLUMN IF NOT EXISTS paid_amount     DECIMAL(10,2) DEFAULT 0 COMMENT '已支付金额';
ALTER TABLE stringing_order ADD COLUMN IF NOT EXISTS pay_method      VARCHAR(20) DEFAULT '' COMMENT '支付方式: CASH-现金 WECHAT-微信 ALIPAY-支付宝 BANK-银行卡 CREDIT-挂账/月结';
ALTER TABLE stringing_order ADD COLUMN IF NOT EXISTS pay_time        TIMESTAMP DEFAULT NULL COMMENT '最后支付时间';
ALTER TABLE stringing_order ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(10,2) DEFAULT 0 COMMENT '优惠金额';
ALTER TABLE stringing_order ADD COLUMN IF NOT EXISTS actual_amount   DECIMAL(10,2) DEFAULT NULL COMMENT '实际应收金额(total_price - discount_amount)';

-- 穿线师绩效字段
ALTER TABLE stringing_order ADD COLUMN IF NOT EXISTS stringer_id    BIGINT DEFAULT NULL COMMENT '穿线师ID（关联sys_user）';
ALTER TABLE stringing_order ADD COLUMN IF NOT EXISTS stringer_name  VARCHAR(50) DEFAULT '' COMMENT '穿线师姓名（冗余，避免JOIN）';
ALTER TABLE stringing_order ADD COLUMN IF NOT EXISTS commission     DECIMAL(10,2) DEFAULT 0 COMMENT '提成金额';

CREATE INDEX IF NOT EXISTS idx_order_stringer ON stringing_order(stringer_id);

-- 通过关联新player表更新已有订单的sport_type
UPDATE stringing_order SET sport_type = p.sport_type
FROM player_new p WHERE stringing_order.player_id = p.id AND stringing_order.sport_type = 'BADMINTON';

-- ----------------------------------------
-- 1.5 tennis_order 数据迁移到 stringing_order
-- ----------------------------------------
-- 获取当前 stringing_order 最大ID
DO $$
DECLARE
    max_order_id BIGINT;
BEGIN
    SELECT COALESCE(MAX(id), 0) INTO max_order_id FROM stringing_order;

    INSERT INTO stringing_order (
        id, tenant_id, order_no, shop_id, player_id, racket_id,
        main_string_id, cross_string_id, player_phone,
        main_tension, cross_tension, main_price, cross_price, labor_price, total_price,
        status, remark, source, printed, print_count, order_photo_url,
        sport_type, pay_status, paid_amount, pay_method, pay_time,
        discount_amount, actual_amount, stringer_id, stringer_name, commission,
        deleted, created_at, updated_at
    )
    SELECT
        max_order_id + ROW_NUMBER() OVER (ORDER BY id),
        tenant_id, order_no, shop_id, player_id, racket_id,
        main_string_id, cross_string_id, player_phone,
        main_tension, cross_tension, main_price, cross_price, labor_price, total_price,
        status, remark, source, printed, print_count, order_photo_url,
        'TENNIS', 'UNPAID', 0, '', NULL,
        0, NULL, NULL, '', 0,
        deleted, created_at, updated_at
    FROM tennis_order;

    -- 更新序列
    PERFORM setval('stringing_order_id_seq', (SELECT MAX(id) FROM stringing_order));
END $$;

-- ----------------------------------------
-- 1.6 重命名表（备份旧表）
-- ----------------------------------------
ALTER TABLE player       RENAME TO player_backup;
ALTER TABLE player_new   RENAME TO player;
ALTER TABLE racket       RENAME TO racket_backup;
ALTER TABLE racket_new   RENAME TO racket;

-- 验证：检查数据量
DO $$
DECLARE
    v_player_count BIGINT;
    v_racket_count BIGINT;
BEGIN
    SELECT COUNT(*) INTO v_player_count FROM player;
    SELECT COUNT(*) INTO v_racket_count FROM racket;
    RAISE NOTICE 'V1.1 迁移验证 - player: % 条, racket: % 条', v_player_count, v_racket_count;
END $$;

-- ============================================================
-- 模块二：库存管理闭环（进销存）
-- ============================================================

-- ----------------------------------------
-- 2.1 stock_log 库存流水表
-- ----------------------------------------
CREATE TABLE IF NOT EXISTS stock_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL COMMENT '租户ID',
    shop_id         BIGINT       NOT NULL COMMENT '店铺ID',
    string_id       BIGINT       NOT NULL COMMENT '线材ID',

    -- 变动信息
    change_type     VARCHAR(20)  NOT NULL COMMENT '变动类型: PURCHASE_IN-采购入库 ORDER_OUT-订单扣减 MANUAL_ADJUST-手动调整 RETURN_IN-退货入库 TRANSFER-调拨',
    quantity        INTEGER      NOT NULL COMMENT '变动数量(正数为入库,负数为出库)',
    before_quantity INTEGER      NOT NULL COMMENT '变动前库存',
    after_quantity  INTEGER      NOT NULL COMMENT '变动后库存',

    -- 关联业务
    order_id        BIGINT       DEFAULT NULL COMMENT '关联订单ID(订单扣减时填写)',
    order_no        VARCHAR(50)  DEFAULT '' COMMENT '关联订单号',

    -- 操作信息
    operator_id     BIGINT       DEFAULT NULL COMMENT '操作人ID',
    operator_name   VARCHAR(50)  DEFAULT '' COMMENT '操作人姓名',
    remark          VARCHAR(200) DEFAULT '' COMMENT '备注(如采购单号、调整原因)',

    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE stock_log IS '库存流水表';
CREATE INDEX idx_stock_log_shop ON stock_log(shop_id);
CREATE INDEX idx_stock_log_string ON stock_log(string_id);
CREATE INDEX idx_stock_log_order ON stock_log(order_id);
CREATE INDEX idx_stock_log_created ON stock_log(created_at);

-- ----------------------------------------
-- 2.2 shop_string 表增加审计字段
-- ----------------------------------------
ALTER TABLE shop_string ADD COLUMN IF NOT EXISTS updated_by BIGINT DEFAULT NULL COMMENT '最后修改人';

-- ============================================================
-- 模块三：财务体系搭建（算清账）
-- ============================================================

-- ----------------------------------------
-- 3.1 payment_record 支付流水表
-- ----------------------------------------
CREATE TABLE IF NOT EXISTS payment_record (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL COMMENT '租户ID',
    order_id        BIGINT       NOT NULL COMMENT '关联订单ID',
    order_no        VARCHAR(50)  NOT NULL COMMENT '订单号',
    player_id       BIGINT       DEFAULT NULL COMMENT '客户ID',
    player_name     VARCHAR(50)  DEFAULT '' COMMENT '客户姓名',

    -- 金额
    amount          DECIMAL(10,2) NOT NULL COMMENT '本次支付金额',
    pay_method      VARCHAR(20)  NOT NULL COMMENT '支付方式: CASH/WECHAT/ALIPAY/BANK/CREDIT',

    -- 支付后状态
    paid_amount_after DECIMAL(10,2) NOT NULL COMMENT '支付后该订单累计已付金额',
    pay_status_after  VARCHAR(20) NOT NULL COMMENT '支付后状态',

    -- 操作信息
    operator_id     BIGINT       DEFAULT NULL COMMENT '收款人ID',
    operator_name   VARCHAR(50)  DEFAULT '' COMMENT '收款人姓名',
    remark          VARCHAR(200) DEFAULT '' COMMENT '备注',

    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE payment_record IS '支付流水表';
CREATE INDEX idx_payment_order ON payment_record(order_id);
CREATE INDEX idx_payment_player ON payment_record(player_id);
CREATE INDEX idx_payment_method ON payment_record(pay_method);
CREATE INDEX idx_payment_created ON payment_record(created_at);

-- ============================================================
-- 模块四：穿线师绩效（算提成）
-- ============================================================

-- ----------------------------------------
-- 4.1 commission_rule 提成规则配置表
-- ----------------------------------------
CREATE TABLE IF NOT EXISTS commission_rule (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL COMMENT '租户ID',
    shop_id         BIGINT       DEFAULT NULL COMMENT '店铺ID(NULL=全局规则)',
    stringer_id     BIGINT       DEFAULT NULL COMMENT '穿线师ID(NULL=默认规则)',

    -- 规则类型
    rule_type       VARCHAR(20)  NOT NULL DEFAULT 'FIXED' COMMENT '规则类型: FIXED-固定金额 PERCENT-百分比 TIERED-阶梯',

    -- 固定金额规则
    fixed_amount    DECIMAL(10,2) DEFAULT 0 COMMENT '固定提成金额(元/支)',

    -- 百分比规则
    percent_rate    DECIMAL(5,2)  DEFAULT 0 COMMENT '提成比例(%, 如 15.00 表示15%)',
    percent_base    VARCHAR(20)  DEFAULT 'LABOR' COMMENT '提成基数: LABOR-手工费 TOTAL-总价 STRING-线材费',

    -- 阶梯规则 (JSON)
    tier_config     JSONB        DEFAULT NULL COMMENT '阶梯配置: [{"min":0,"max":50,"amount":10},{"min":50,"max":null,"amount":15}]',

    -- 生效时间
    effective_from  DATE         NOT NULL DEFAULT CURRENT_DATE,
    effective_to    DATE         DEFAULT NULL COMMENT 'NULL=永久有效',

    enabled         SMALLINT     NOT NULL DEFAULT 1,
    remark          VARCHAR(200) DEFAULT '',
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE commission_rule IS '提成规则配置表';

-- ============================================================
-- 插入默认提成规则（示例）
-- ============================================================
INSERT INTO commission_rule (tenant_id, rule_type, fixed_amount, percent_rate, percent_base, effective_from, remark)
VALUES
    (NULL, 'FIXED', 15.00, 0, 'LABOR', CURRENT_DATE, '默认固定提成：15元/支'),
    (NULL, 'PERCENT', 0, 30.00, 'LABOR', CURRENT_DATE, '默认百分比提成：手工费30%'),
    (NULL, 'TIERED', 0, 0, 'LABOR', CURRENT_DATE, '默认阶梯提成：月≤50支10元,>50支15元');

-- ============================================================
-- 迁移完成提示
-- ============================================================
-- 以下为验证步骤，确认无误后再执行旧表删除：
-- SELECT COUNT(*) FROM player_backup;       -- 原羽毛球player数量
-- SELECT COUNT(*) FROM tennis_player;        -- 原网球player数量
-- SELECT COUNT(*) FROM player;               -- 合并后应 = 两者之和
-- SELECT COUNT(*) FROM racket_backup;        -- 原羽毛球racket数量
-- SELECT COUNT(*) FROM tennis_racket;        -- 原网球racket数量
-- SELECT COUNT(*) FROM racket;               -- 合并后应 = 两者之和

-- 验证通过后，可执行以下语句清理旧表（⚠️ 谨慎操作！）：
-- DROP TABLE IF EXISTS tennis_player CASCADE;
-- DROP TABLE IF EXISTS tennis_racket CASCADE;
-- DROP TABLE IF EXISTS tennis_string_info CASCADE;
-- DROP TABLE IF EXISTS tennis_order CASCADE;
-- DROP TABLE IF EXISTS player_backup CASCADE;
-- DROP TABLE IF EXISTS racket_backup CASCADE;

COMMIT;
