-- ============================================================
-- 三益穿线管理系统 V1.1 数据库迁移脚本 (PostgreSQL 修正版)
-- 已修复：移除 MySQL 内联 COMMENT 语法，改用 PostgreSQL 标准语法
-- ============================================================

BEGIN;

-- ============================================================
-- 模块一：数据模型重构（羽网合并）
-- ============================================================

-- ----------------------------------------
-- 1.1 统一 player 表（原 player + tennis_player 合并）
-- ----------------------------------------
CREATE TABLE player_new (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(50)  NOT NULL,
    phone           VARCHAR(20)  NOT NULL DEFAULT '',
    gender          SMALLINT     DEFAULT 0,
    sport_type      VARCHAR(10)  NOT NULL DEFAULT 'BADMINTON',
    ranking         VARCHAR(50)  DEFAULT '',
    photo_url       VARCHAR(500) DEFAULT '',
    skill_level     VARCHAR(20)  DEFAULT '',
    progress_notes  TEXT         DEFAULT '',
    remark          VARCHAR(500) DEFAULT '',
    country         VARCHAR(50)  DEFAULT '',
    tenant_id       BIGINT       DEFAULT NULL,
    deleted         SMALLINT     NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE player_new IS '统一球员表（羽毛球+网球）';
COMMENT ON COLUMN player_new.gender IS '0-未知 1-男 2-女';
COMMENT ON COLUMN player_new.sport_type IS '运动类型: BADMINTON-羽毛球 TENNIS-网球 DUAL-双修';
COMMENT ON COLUMN player_new.ranking IS '网球排名（仅网球有效）';
COMMENT ON COLUMN player_new.skill_level IS '水平等级';
COMMENT ON COLUMN player_new.progress_notes IS '近期进步/备注';
COMMENT ON COLUMN player_new.country IS '国家/地区';
COMMENT ON COLUMN player_new.tenant_id IS '所属租户';
CREATE INDEX idx_player_phone ON player_new(phone);
CREATE INDEX idx_player_tenant ON player_new(tenant_id);
CREATE INDEX idx_player_sport ON player_new(sport_type);

-- 迁移羽毛球 player 数据
INSERT INTO player_new (id, name, phone, gender, sport_type, ranking, photo_url,
                         skill_level, progress_notes, remark, country, tenant_id, deleted, created_at, updated_at)
SELECT id, name, phone, gender, 'BADMINTON', '', photo_url, skill_level, progress_notes,
       remark, '', NULL, deleted, created_at, updated_at
FROM player;

-- 更新序列值（必须在插入网球数据之前！）
SELECT setval('player_new_id_seq', (SELECT MAX(id) FROM player_new));

-- 迁移网球 tennis_player 数据（不指定id，使用新序列）
INSERT INTO player_new (name, phone, gender, sport_type, ranking, photo_url,
                         skill_level, progress_notes, remark, country, tenant_id, deleted, created_at, updated_at)
SELECT name, phone, gender, 'TENNIS', ranking, photo_url, skill_level, progress_notes,
       remark, '', NULL, deleted, created_at, updated_at
FROM tennis_player;

-- ----------------------------------------
-- 1.2 统一 racket 表（原 racket + tennis_racket 合并）
-- ----------------------------------------
CREATE TABLE racket_new (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sport_type      VARCHAR(10)  NOT NULL DEFAULT 'BADMINTON',
    brand           VARCHAR(100) NOT NULL,
    model           VARCHAR(100) NOT NULL DEFAULT '',
    spec            VARCHAR(50)  DEFAULT '',
    head_size       VARCHAR(20)  DEFAULT '',
    string_pattern  VARCHAR(20)  DEFAULT '',
    weight          VARCHAR(20)  DEFAULT '',
    balance         VARCHAR(20)  DEFAULT '',
    remark          VARCHAR(500) DEFAULT '',
    tenant_id       BIGINT       DEFAULT NULL,
    deleted         SMALLINT     NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE racket_new IS '统一球拍表（羽毛球+网球）';
COMMENT ON COLUMN racket_new.sport_type IS '运动类型';
COMMENT ON COLUMN racket_new.spec IS '羽毛球规格(如 4U/3U/G5)';
COMMENT ON COLUMN racket_new.head_size IS '拍面大小(平方英寸)';
COMMENT ON COLUMN racket_new.string_pattern IS '线床规格(如 16x19)';
COMMENT ON COLUMN racket_new.weight IS '空拍重量(克)';
COMMENT ON COLUMN racket_new.balance IS '平衡点(mm)';
CREATE INDEX idx_racket_brand ON racket_new(brand);
CREATE INDEX idx_racket_sport ON racket_new(sport_type);

-- 迁移羽毛球 racket 数据
INSERT INTO racket_new (id, sport_type, brand, model, spec, head_size, string_pattern, weight, balance, remark, tenant_id, deleted, created_at, updated_at)
SELECT id, 'BADMINTON', brand, model, spec, '', '', '', '', remark, NULL, deleted, created_at, updated_at
FROM racket;

-- 更新序列值（必须在插入网球数据之前！）
SELECT setval('racket_new_id_seq', (SELECT MAX(id) FROM racket_new));

-- 迁移网球 tennis_racket 数据
INSERT INTO racket_new (sport_type, brand, model, spec, head_size, string_pattern, weight, balance, remark, tenant_id, deleted, created_at, updated_at)
SELECT 'TENNIS', brand, model, '', head_size, string_pattern, weight, '', remark, NULL, deleted, created_at, updated_at
FROM tennis_racket;

-- ----------------------------------------
-- 1.3 string_info 表增加字段（原地修改）
-- ----------------------------------------
ALTER TABLE string_info ADD COLUMN IF NOT EXISTS sport_type VARCHAR(10) NOT NULL DEFAULT 'BADMINTON';
ALTER TABLE string_info ADD COLUMN IF NOT EXISTS tenant_id  BIGINT DEFAULT NULL;
COMMENT ON COLUMN string_info.sport_type IS '运动类型: BADMINTON-羽毛球 TENNIS-网球';
COMMENT ON COLUMN string_info.tenant_id IS '所属租户';
CREATE INDEX IF NOT EXISTS idx_string_sport ON string_info(sport_type);
CREATE INDEX IF NOT EXISTS idx_string_tenant ON string_info(tenant_id);

-- 迁移网球 tennis_string_info 数据
INSERT INTO string_info (brand, model, color, diameter, sport_type, remark, deleted, created_at, updated_at)
SELECT brand, model, color, NULL, 'TENNIS', remark, deleted, created_at, updated_at
FROM tennis_string_info;

-- ----------------------------------------
-- 1.4 stringing_order 表改造（新增字段 + sport_type）
-- ----------------------------------------
ALTER TABLE stringing_order ADD COLUMN IF NOT EXISTS sport_type VARCHAR(10) NOT NULL DEFAULT 'BADMINTON';
COMMENT ON COLUMN stringing_order.sport_type IS '运动类型';
CREATE INDEX IF NOT EXISTS idx_order_sport ON stringing_order(sport_type);

ALTER TABLE stringing_order ADD COLUMN IF NOT EXISTS pay_status      VARCHAR(20) NOT NULL DEFAULT 'UNPAID';
ALTER TABLE stringing_order ADD COLUMN IF NOT EXISTS paid_amount     DECIMAL(10,2) DEFAULT 0;
ALTER TABLE stringing_order ADD COLUMN IF NOT EXISTS pay_method      VARCHAR(20) DEFAULT '';
ALTER TABLE stringing_order ADD COLUMN IF NOT EXISTS pay_time        TIMESTAMP DEFAULT NULL;
ALTER TABLE stringing_order ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(10,2) DEFAULT 0;
ALTER TABLE stringing_order ADD COLUMN IF NOT EXISTS actual_amount   DECIMAL(10,2) DEFAULT NULL;
COMMENT ON COLUMN stringing_order.pay_status IS '支付状态: UNPAID-未付 PARTIAL-部分支付 PAID-已结清 CREDIT-挂账';
COMMENT ON COLUMN stringing_order.paid_amount IS '已支付金额';
COMMENT ON COLUMN stringing_order.pay_method IS '支付方式: CASH-现金 WECHAT-微信 ALIPAY-支付宝 BANK-银行卡 CREDIT-挂账/月结';
COMMENT ON COLUMN stringing_order.pay_time IS '最后支付时间';
COMMENT ON COLUMN stringing_order.discount_amount IS '优惠金额';
COMMENT ON COLUMN stringing_order.actual_amount IS '实际应收金额(total_price - discount_amount)';

ALTER TABLE stringing_order ADD COLUMN IF NOT EXISTS stringer_id    BIGINT DEFAULT NULL;
ALTER TABLE stringing_order ADD COLUMN IF NOT EXISTS stringer_name  VARCHAR(50) DEFAULT '';
ALTER TABLE stringing_order ADD COLUMN IF NOT EXISTS commission     DECIMAL(10,2) DEFAULT 0;
COMMENT ON COLUMN stringing_order.stringer_id IS '穿线师ID（关联sys_user）';
COMMENT ON COLUMN stringing_order.stringer_name IS '穿线师姓名（冗余，避免JOIN）';
COMMENT ON COLUMN stringing_order.commission IS '提成金额';

CREATE INDEX IF NOT EXISTS idx_order_stringer ON stringing_order(stringer_id);

-- 通过关联新player表更新已有订单的sport_type
UPDATE stringing_order SET sport_type = p.sport_type
FROM player_new p WHERE stringing_order.player_id = p.id AND stringing_order.sport_type = 'BADMINTON';

-- ----------------------------------------
-- 1.5 tennis_order 数据迁移到 stringing_order
-- ----------------------------------------
DO $$
DECLARE
    max_order_id BIGINT;
BEGIN
    SELECT COALESCE(MAX(id), 0) INTO max_order_id FROM stringing_order;

    INSERT INTO stringing_order (
        id, tenant_id, order_no, shop_id, player_id, racket_id,
        main_string_id, cross_string_id, player_phone,
        main_tension, cross_tension, main_price, cross_price, labor_price, total_price,
        status, remark, source, printed, print_count, order_photo_url,
        sport_type, pay_status, paid_amount, pay_method, pay_time,
        discount_amount, actual_amount, stringer_id, stringer_name, commission,
        deleted, created_at, updated_at
    )
    SELECT
        max_order_id + ROW_NUMBER() OVER (ORDER BY id),
        tenant_id, order_no, shop_id, player_id, racket_id,
        main_string_id, cross_string_id, player_phone,
        main_tension, cross_tension, main_price, cross_price, labor_price, total_price,
        status, remark, source, printed, print_count, order_photo_url,
        'TENNIS', 'UNPAID', 0, '', NULL,
        0, NULL, NULL, '', 0,
        deleted, created_at, updated_at
    FROM tennis_order;

    PERFORM setval('stringing_order_id_seq', (SELECT MAX(id) FROM stringing_order));
END $$;

-- ----------------------------------------
-- 1.6 重命名表（备份旧表）
-- ----------------------------------------
ALTER TABLE player       RENAME TO player_backup;
ALTER TABLE player_new   RENAME TO player;
ALTER TABLE racket       RENAME TO racket_backup;
ALTER TABLE racket_new   RENAME TO racket;

-- 验证：检查数据量
DO $$
DECLARE
    v_player_count BIGINT;
    v_racket_count BIGINT;
BEGIN
    SELECT COUNT(*) INTO v_player_count FROM player;
    SELECT COUNT(*) INTO v_racket_count FROM racket;
    RAISE NOTICE 'V1.1 迁移验证 - player: % 条, racket: % 条', v_player_count, v_racket_count;
END $$;

-- ============================================================
-- 模块二：库存管理闭环（进销存）
-- ============================================================

-- ----------------------------------------
-- 2.1 stock_log 库存流水表
-- ----------------------------------------
CREATE TABLE IF NOT EXISTS stock_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL,
    shop_id         BIGINT       NOT NULL,
    string_id       BIGINT       NOT NULL,
    change_type     VARCHAR(20)  NOT NULL,
    quantity        INTEGER      NOT NULL,
    before_quantity INTEGER      NOT NULL,
    after_quantity  INTEGER      NOT NULL,
    order_id        BIGINT       DEFAULT NULL,
    order_no        VARCHAR(50)  DEFAULT '',
    operator_id     BIGINT       DEFAULT NULL,
    operator_name   VARCHAR(50)  DEFAULT '',
    remark          VARCHAR(200) DEFAULT '',
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE stock_log IS '库存流水表';
COMMENT ON COLUMN stock_log.tenant_id IS '租户ID';
COMMENT ON COLUMN stock_log.shop_id IS '店铺ID';
COMMENT ON COLUMN stock_log.string_id IS '线材ID';
COMMENT ON COLUMN stock_log.change_type IS '变动类型: PURCHASE_IN-采购入库 ORDER_OUT-订单扣减 MANUAL_ADJUST-手动调整 RETURN_IN-退货入库 TRANSFER-调拨';
COMMENT ON COLUMN stock_log.quantity IS '变动数量(正数为入库,负数为出库)';
COMMENT ON COLUMN stock_log.before_quantity IS '变动前库存';
COMMENT ON COLUMN stock_log.after_quantity IS '变动后库存';
COMMENT ON COLUMN stock_log.order_id IS '关联订单ID(订单扣减时填写)';
COMMENT ON COLUMN stock_log.order_no IS '关联订单号';
COMMENT ON COLUMN stock_log.operator_id IS '操作人ID';
COMMENT ON COLUMN stock_log.operator_name IS '操作人姓名';
COMMENT ON COLUMN stock_log.remark IS '备注(如采购单号、调整原因)';
CREATE INDEX idx_stock_log_shop ON stock_log(shop_id);
CREATE INDEX idx_stock_log_string ON stock_log(string_id);
CREATE INDEX idx_stock_log_order ON stock_log(order_id);
CREATE INDEX idx_stock_log_created ON stock_log(created_at);

-- ----------------------------------------
-- 2.2 shop_string 表增加审计字段
-- ----------------------------------------
ALTER TABLE shop_string ADD COLUMN IF NOT EXISTS updated_by BIGINT DEFAULT NULL;
COMMENT ON COLUMN shop_string.updated_by IS '最后修改人';

-- ============================================================
-- 模块三：财务体系搭建（算清账）
-- ============================================================

-- ----------------------------------------
-- 3.1 payment_record 支付流水表
-- ----------------------------------------
CREATE TABLE IF NOT EXISTS payment_record (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL,
    order_id        BIGINT       NOT NULL,
    order_no        VARCHAR(50)  NOT NULL,
    player_id       BIGINT       DEFAULT NULL,
    player_name     VARCHAR(50)  DEFAULT '',
    amount          DECIMAL(10,2) NOT NULL,
    pay_method      VARCHAR(20)  NOT NULL,
    paid_amount_after DECIMAL(10,2) NOT NULL,
    pay_status_after  VARCHAR(20) NOT NULL,
    operator_id     BIGINT       DEFAULT NULL,
    operator_name   VARCHAR(50)  DEFAULT '',
    remark          VARCHAR(200) DEFAULT '',
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE payment_record IS '支付流水表';
COMMENT ON COLUMN payment_record.tenant_id IS '租户ID';
COMMENT ON COLUMN payment_record.order_id IS '关联订单ID';
COMMENT ON COLUMN payment_record.order_no IS '订单号';
COMMENT ON COLUMN payment_record.player_id IS '客户ID';
COMMENT ON COLUMN payment_record.player_name IS '客户姓名';
COMMENT ON COLUMN payment_record.amount IS '本次支付金额';
COMMENT ON COLUMN payment_record.pay_method IS '支付方式: CASH/WECHAT/ALIPAY/BANK/CREDIT';
COMMENT ON COLUMN payment_record.paid_amount_after IS '支付后该订单累计已付金额';
COMMENT ON COLUMN payment_record.pay_status_after IS '支付后状态';
COMMENT ON COLUMN payment_record.operator_id IS '收款人ID';
COMMENT ON COLUMN payment_record.operator_name IS '收款人姓名';
COMMENT ON COLUMN payment_record.remark IS '备注';
CREATE INDEX idx_payment_order ON payment_record(order_id);
CREATE INDEX idx_payment_player ON payment_record(player_id);
CREATE INDEX idx_payment_method ON payment_record(pay_method);
CREATE INDEX idx_payment_created ON payment_record(created_at);

-- ============================================================
-- 模块四：穿线师绩效（算提成）
-- ============================================================

-- ----------------------------------------
-- 4.1 commission_rule 提成规则配置表
-- ----------------------------------------
CREATE TABLE IF NOT EXISTS commission_rule (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       DEFAULT NULL,
    shop_id         BIGINT       DEFAULT NULL,
    stringer_id     BIGINT       DEFAULT NULL,
    rule_type       VARCHAR(20)  NOT NULL DEFAULT 'FIXED',
    fixed_amount    DECIMAL(10,2) DEFAULT 0,
    percent_rate    DECIMAL(5,2)  DEFAULT 0,
    percent_base    VARCHAR(20)  DEFAULT 'LABOR',
    tier_config     JSONB        DEFAULT NULL,
    effective_from  DATE         NOT NULL DEFAULT CURRENT_DATE,
    effective_to    DATE         DEFAULT NULL,
    enabled         SMALLINT     NOT NULL DEFAULT 1,
    remark          VARCHAR(200) DEFAULT '',
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE commission_rule IS '提成规则配置表';
COMMENT ON COLUMN commission_rule.tenant_id IS '租户ID';
COMMENT ON COLUMN commission_rule.shop_id IS '店铺ID(NULL=全局规则)';
COMMENT ON COLUMN commission_rule.stringer_id IS '穿线师ID(NULL=默认规则)';
COMMENT ON COLUMN commission_rule.rule_type IS '规则类型: FIXED-固定金额 PERCENT-百分比 TIERED-阶梯';
COMMENT ON COLUMN commission_rule.fixed_amount IS '固定提成金额(元/支)';
COMMENT ON COLUMN commission_rule.percent_rate IS '提成比例(%, 如 15.00 表示15%)';
COMMENT ON COLUMN commission_rule.percent_base IS '提成基数: LABOR-手工费 TOTAL-总价 STRING-线材费';
COMMENT ON COLUMN commission_rule.tier_config IS '阶梯配置 JSON';
COMMENT ON COLUMN commission_rule.effective_to IS 'NULL=永久有效';

-- ============================================================
-- 插入默认提成规则（示例）
-- ============================================================
INSERT INTO commission_rule (tenant_id, rule_type, fixed_amount, percent_rate, percent_base, effective_from, remark)
VALUES
    (NULL, 'FIXED', 15.00, 0, 'LABOR', CURRENT_DATE, '默认固定提成：15元/支'),
    (NULL, 'PERCENT', 0, 30.00, 'LABOR', CURRENT_DATE, '默认百分比提成：手工费30%'),
    (NULL, 'TIERED', 0, 0, 'LABOR', CURRENT_DATE, '默认阶梯提成：月≤50支10元,>50支15元');

COMMIT;
