-- ============================================================
-- V2.0 供应商管理模块
-- ============================================================

CREATE TABLE IF NOT EXISTS supplier (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    contact_person  VARCHAR(50)  DEFAULT '',
    phone           VARCHAR(20)  DEFAULT '',
    email           VARCHAR(100) DEFAULT '',
    address         VARCHAR(500) DEFAULT '',
    sport_type      VARCHAR(10)  NOT NULL DEFAULT 'BADMINTON',
    remark          VARCHAR(500) DEFAULT '',
    tenant_id       BIGINT       DEFAULT NULL,
    deleted         SMALLINT     NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE supplier IS '供应商表';
CREATE INDEX IF NOT EXISTS idx_supplier_name ON supplier(name);
CREATE INDEX IF NOT EXISTS idx_supplier_tenant ON supplier(tenant_id);
CREATE INDEX IF NOT EXISTS idx_supplier_sport ON supplier(sport_type);
