-- V1.5 Missing Tables Creation
-- Fixes: Inbound Order, Inbound Item, Inventory Stock

BEGIN;

-- 1. 入库单主表
CREATE TABLE IF NOT EXISTS inbound_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    shop_id BIGINT NOT NULL,
    operator_id BIGINT,
    operator_name VARCHAR(50),
    total_quantity INT DEFAULT 0,
    total_cost NUMERIC(10, 2) DEFAULT 0.00,
    remark VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. 入库单明细表
CREATE TABLE IF NOT EXISTS inbound_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    order_id BIGINT NOT NULL REFERENCES inbound_order(id),
    string_id BIGINT,
    string_name VARCHAR(100),
    quantity INT NOT NULL,
    cost_price NUMERIC(10, 2),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. 库存表 (Code expects 'inventory_stock', DB has 'inventory_goods')
-- We create inventory_stock to match the code. 
CREATE TABLE IF NOT EXISTS inventory_stock (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku_code VARCHAR(50),
    sku_name VARCHAR(100),
    total_stock INT DEFAULT 0,
    reserved_stock INT DEFAULT 0,
    available_stock INT DEFAULT 0,
    status INT DEFAULT 1,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
