-- ============================================================
-- 补全 V1.4/V1.5 缺失的表结构
-- 生成时间: 2026-05-11
-- ============================================================

-- 1. 打印策略表 (sys_print_policy)
CREATE TABLE IF NOT EXISTS sys_print_policy (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id     BIGINT       DEFAULT NULL,
    rule_name   VARCHAR(100) NOT NULL,
    doc_type    VARCHAR(50)  NOT NULL,
    printer_id  BIGINT,
    template_id BIGINT,
    priority    INT          DEFAULT 0,
    status      SMALLINT     DEFAULT 1,
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE sys_print_policy IS '打印策略表';
CREATE INDEX idx_policy_shop ON sys_print_policy(shop_id);

-- 2. 打印日志表 (print_log) - V1.4
CREATE TABLE IF NOT EXISTS print_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT,
    operator_id BIGINT,
    type        VARCHAR(50),
    status      VARCHAR(20),
    reprint_type VARCHAR(20),
    remark      VARCHAR(255),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE print_log IS '打印日志表';

-- 3. 供应商表 (supplier) - V1.5
CREATE TABLE IF NOT EXISTS supplier (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name           VARCHAR(100) NOT NULL,
    contact_person VARCHAR(50),
    phone          VARCHAR(20),
    address        VARCHAR(255),
    status         SMALLINT DEFAULT 1,
    created_at     TIMESTAMP  DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP  DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE supplier IS '供应商管理';

-- 4. 库存商品表 (inventory_goods) - V1.5
CREATE TABLE IF NOT EXISTS inventory_goods (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id     BIGINT,
    item_name   VARCHAR(100) NOT NULL,
    category    VARCHAR(50),
    unit        VARCHAR(20),
    current_qty INT          DEFAULT 0,
    alert_qty   INT          DEFAULT 10,
    price       NUMERIC(10,2),
    status      SMALLINT     DEFAULT 1,
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE inventory_goods IS '库存商品台账';

-- 5. 技师工作记录表 (stringer_work_log) - V1.5
CREATE TABLE IF NOT EXISTS stringer_work_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shop_id       BIGINT,
    stringer_id   BIGINT,
    order_id      BIGINT,
    work_date     DATE,
    racket_model  VARCHAR(100),
    string_type   VARCHAR(100),
    tension       VARCHAR(20),
    duration_min  INT,
    is_completed  BOOLEAN    DEFAULT FALSE,
    created_at    TIMESTAMP  DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE stringer_work_log IS '穿线师绩效记录';

-- 初始化默认数据
INSERT INTO supplier (name, contact_person, phone) VALUES ('尤尼克斯总代', '张经理', '13800138000') ON CONFLICT DO NOTHING;
INSERT INTO inventory_goods (shop_id, item_name, category, unit, current_qty, price) VALUES (1, 'YONEX BG65', 'LINE', 'Piece', 50, 35.00) ON CONFLICT DO NOTHING;
