-- V1.5 Missing Tables Patch (Part 2)
-- Fixes: Print Task Log, Print Template

BEGIN;

-- 4. 打印任务日志表
CREATE TABLE IF NOT EXISTS print_task_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id VARCHAR(100),
    order_id BIGINT,
    printer_sn VARCHAR(50),
    status INT DEFAULT 0, -- 0-pending, 1-success, 2-failed
    error_msg TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. 打印模板表 (Code expects 'sys_print_template', DB has none)
CREATE TABLE IF NOT EXISTS sys_print_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    name VARCHAR(100) NOT NULL,
    content TEXT, -- Template JSON/HTML content
    type VARCHAR(20) DEFAULT 'STANDARD', -- STANDARD, RECEIPT, etc.
    status INT DEFAULT 1,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
