-- V1.5 Missing Tables Patch (Corrected)
-- Fixes: Print Task Log, Print Template (Full Schema)

BEGIN;

-- 4. 打印任务日志表
CREATE TABLE IF NOT EXISTS print_task_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id VARCHAR(100),
    order_id BIGINT,
    tenant_id BIGINT,
    printer_sn VARCHAR(50),
    status INT DEFAULT 0, -- 0-pending, 1-success, 2-failed
    result_msg TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. 打印模板表 (Full Schema matching PrintTemplate.java)
CREATE TABLE IF NOT EXISTS sys_print_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT,
    shop_id BIGINT,
    name VARCHAR(100) NOT NULL,
    content TEXT, -- V1.4 新增 JSON 模板内容
    paper_width INT,
    paper_height INT,
    font_size INT,
    show_logo INT DEFAULT 1,
    show_qrcode INT DEFAULT 1,
    fields_json TEXT,
    status INT DEFAULT 1, -- V1.5 新增状态字段
    is_default INT DEFAULT 0,
    deleted INT DEFAULT 0,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
