-- ============================================================
-- V2.2 操作日志表
-- 用于记录用户的关键操作，便于审计和追踪
-- ============================================================

CREATE TABLE IF NOT EXISTS operate_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       DEFAULT NULL,
    user_id         BIGINT       DEFAULT NULL,
    username        VARCHAR(50)  DEFAULT '',
    module          VARCHAR(50)  DEFAULT '',
    operation       VARCHAR(50)  DEFAULT '',
    target_type     VARCHAR(50)  DEFAULT '',
    target_id       BIGINT       DEFAULT NULL,
    detail          TEXT         DEFAULT '',
    ip              VARCHAR(50)  DEFAULT '',
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 索引：按租户查询
CREATE INDEX IF NOT EXISTS idx_operate_log_tenant ON operate_log(tenant_id);

-- 索引：按用户查询
CREATE INDEX IF NOT EXISTS idx_operate_log_user ON operate_log(user_id);

-- 索引：按模块查询
CREATE INDEX IF NOT EXISTS idx_operate_log_module ON operate_log(module);

-- 索引：按时间查询（降序）
CREATE INDEX IF NOT EXISTS idx_operate_log_time ON operate_log(created_at DESC);

-- 索引：按目标资源查询
CREATE INDEX IF NOT EXISTS idx_operate_log_target ON operate_log(target_type, target_id);

COMMENT ON TABLE operate_log IS '操作日志表 - 记录用户关键操作';
COMMENT ON COLUMN operate_log.id IS '主键 ID';
COMMENT ON COLUMN operate_log.tenant_id IS '租户 ID';
COMMENT ON COLUMN operate_log.user_id IS '操作用户 ID';
COMMENT ON COLUMN operate_log.username IS '操作用户名';
COMMENT ON COLUMN operate_log.module IS '模块名称（如：订单管理、库存管理）';
COMMENT ON COLUMN operate_log.operation IS '操作类型（如：create、update、delete）';
COMMENT ON COLUMN operate_log.target_type IS '目标资源类型（如：order、stock）';
COMMENT ON COLUMN operate_log.target_id IS '目标资源 ID';
COMMENT ON COLUMN operate_log.detail IS '操作详情';
COMMENT ON COLUMN operate_log.ip IS '操作 IP 地址';
COMMENT ON COLUMN operate_log.created_at IS '操作时间';
